# Generated by Django 5.0.6 on 2024-05-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapiapp', '0002_recommendation_alter_userinteraction_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
